<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.6.0 on win32)" generated="20200311 10:11:33.081" rpa="false">
<suite id="s1" name="SETTEXT" source="C:\Users\LIJAMANNATHARA\PycharmProjects\UIAF_UI\java\RobotFramework\SETTEXT.robot">
<test id="s1-t1" name="SETTEXT">
<kw name="Connect To Session" library="SapGuiLibrary">
<doc>Connects to an open session SAP.</doc>
<status status="PASS" starttime="20200311 10:11:33.344" endtime="20200311 10:11:33.373"></status>
</kw>
<kw name="Connect To Existing Connection" library="SapGuiLibrary">
<doc>Connects to an open connection. If the connection matches the given connection_name, the session is connected
to this connection.</doc>
<arguments>
<arg>${connection_name}</arg>
</arguments>
<msg timestamp="20200311 10:11:33.422" level="FAIL">com_error: (-2147352567, 'Exception occurred.', (614, 'saplogon', 'The enumerator of the collection cannot find en element with the specified index.', 'C:\\Program Files (x86)\\SAP\\FrontEnd\\SapGui\\saplogon.HLP', 393215, 0), None)</msg>
<status status="FAIL" starttime="20200311 10:11:33.375" endtime="20200311 10:11:33.422"></status>
</kw>
<status status="FAIL" starttime="20200311 10:11:33.343" endtime="20200311 10:11:33.432" critical="yes">com_error: (-2147352567, 'Exception occurred.', (614, 'saplogon', 'The enumerator of the collection cannot find en element with the specified index.', 'C:\\Program Files (x86)\\SAP\\FrontEnd\\SapGui\\saplogon.HLP', 393215, 0), None)</status>
</test>
<status status="FAIL" starttime="20200311 10:11:33.086" endtime="20200311 10:11:33.435"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="SETTEXT">SETTEXT</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
